// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: question_set_msg.proto

package edupb

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type QueSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaperId       string               `protobuf:"bytes,1,opt,name=paper_id,json=paperId,proto3" json:"paper_id,omitempty"`
	PaperType     string               `protobuf:"bytes,2,opt,name=paper_type,json=paperType,proto3" json:"paper_type,omitempty"`
	PaperName     string               `protobuf:"bytes,3,opt,name=paper_name,json=paperName,proto3" json:"paper_name,omitempty"`
	PaperDuration uint32               `protobuf:"varint,4,opt,name=paper_duration,json=paperDuration,proto3" json:"paper_duration,omitempty"`
	Questions     []*QueSet_Question   `protobuf:"bytes,5,rep,name=questions,proto3" json:"questions,omitempty"`
	UpdatedAt     *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *QueSet) Reset() {
	*x = QueSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_question_set_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueSet) ProtoMessage() {}

func (x *QueSet) ProtoReflect() protoreflect.Message {
	mi := &file_question_set_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueSet.ProtoReflect.Descriptor instead.
func (*QueSet) Descriptor() ([]byte, []int) {
	return file_question_set_msg_proto_rawDescGZIP(), []int{0}
}

func (x *QueSet) GetPaperId() string {
	if x != nil {
		return x.PaperId
	}
	return ""
}

func (x *QueSet) GetPaperType() string {
	if x != nil {
		return x.PaperType
	}
	return ""
}

func (x *QueSet) GetPaperName() string {
	if x != nil {
		return x.PaperName
	}
	return ""
}

func (x *QueSet) GetPaperDuration() uint32 {
	if x != nil {
		return x.PaperDuration
	}
	return 0
}

func (x *QueSet) GetQuestions() []*QueSet_Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *QueSet) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type QueSet_Answer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnswerId      string `protobuf:"bytes,1,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	AnswerValue   string `protobuf:"bytes,2,opt,name=answer_value,json=answerValue,proto3" json:"answer_value,omitempty"`
	CorrectAnswer string `protobuf:"bytes,3,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"`
}

func (x *QueSet_Answer) Reset() {
	*x = QueSet_Answer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_question_set_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueSet_Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueSet_Answer) ProtoMessage() {}

func (x *QueSet_Answer) ProtoReflect() protoreflect.Message {
	mi := &file_question_set_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueSet_Answer.ProtoReflect.Descriptor instead.
func (*QueSet_Answer) Descriptor() ([]byte, []int) {
	return file_question_set_msg_proto_rawDescGZIP(), []int{0, 0}
}

func (x *QueSet_Answer) GetAnswerId() string {
	if x != nil {
		return x.AnswerId
	}
	return ""
}

func (x *QueSet_Answer) GetAnswerValue() string {
	if x != nil {
		return x.AnswerValue
	}
	return ""
}

func (x *QueSet_Answer) GetCorrectAnswer() string {
	if x != nil {
		return x.CorrectAnswer
	}
	return ""
}

type QueSet_Question struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestionId    string           `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	QuestionValue string           `protobuf:"bytes,2,opt,name=question_value,json=questionValue,proto3" json:"question_value,omitempty"`
	Answers       []*QueSet_Answer `protobuf:"bytes,4,rep,name=answers,proto3" json:"answers,omitempty"`
}

func (x *QueSet_Question) Reset() {
	*x = QueSet_Question{}
	if protoimpl.UnsafeEnabled {
		mi := &file_question_set_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueSet_Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueSet_Question) ProtoMessage() {}

func (x *QueSet_Question) ProtoReflect() protoreflect.Message {
	mi := &file_question_set_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueSet_Question.ProtoReflect.Descriptor instead.
func (*QueSet_Question) Descriptor() ([]byte, []int) {
	return file_question_set_msg_proto_rawDescGZIP(), []int{0, 1}
}

func (x *QueSet_Question) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *QueSet_Question) GetQuestionValue() string {
	if x != nil {
		return x.QuestionValue
	}
	return ""
}

func (x *QueSet_Question) GetAnswers() []*QueSet_Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

var File_question_set_msg_proto protoreflect.FileDescriptor

var file_question_set_msg_proto_rawDesc = []byte{
	0x0a, 0x16, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x6d,
	0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x65, 0x64, 0x75, 0x5f, 0x70, 0x61,
	0x70, 0x65, 0x72, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf7, 0x03, 0x0a, 0x06, 0x51, 0x75, 0x65, 0x53, 0x65, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x61, 0x70, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61,
	0x70, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x61, 0x70, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x70,
	0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x61, 0x70, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x70, 0x65,
	0x72, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0d, 0x70, 0x61, 0x70, 0x65, 0x72, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x38, 0x0a, 0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x65, 0x64, 0x75, 0x5f, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x51,
	0x75, 0x65, 0x53, 0x65, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x1a, 0x6f, 0x0a, 0x06, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x1b,
	0x0a, 0x09, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x25,
	0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x1a, 0x86, 0x01, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x61, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x65, 0x64,
	0x75, 0x5f, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x65, 0x53, 0x65, 0x74, 0x2e, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x3b, 0x65, 0x64, 0x75, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_question_set_msg_proto_rawDescOnce sync.Once
	file_question_set_msg_proto_rawDescData = file_question_set_msg_proto_rawDesc
)

func file_question_set_msg_proto_rawDescGZIP() []byte {
	file_question_set_msg_proto_rawDescOnce.Do(func() {
		file_question_set_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_question_set_msg_proto_rawDescData)
	})
	return file_question_set_msg_proto_rawDescData
}

var file_question_set_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_question_set_msg_proto_goTypes = []interface{}{
	(*QueSet)(nil),              // 0: edu_paper.QueSet
	(*QueSet_Answer)(nil),       // 1: edu_paper.QueSet.Answer
	(*QueSet_Question)(nil),     // 2: edu_paper.QueSet.Question
	(*timestamp.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_question_set_msg_proto_depIdxs = []int32{
	2, // 0: edu_paper.QueSet.questions:type_name -> edu_paper.QueSet.Question
	3, // 1: edu_paper.QueSet.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: edu_paper.QueSet.Question.answers:type_name -> edu_paper.QueSet.Answer
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_question_set_msg_proto_init() }
func file_question_set_msg_proto_init() {
	if File_question_set_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_question_set_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_question_set_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueSet_Answer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_question_set_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueSet_Question); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_question_set_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_question_set_msg_proto_goTypes,
		DependencyIndexes: file_question_set_msg_proto_depIdxs,
		MessageInfos:      file_question_set_msg_proto_msgTypes,
	}.Build()
	File_question_set_msg_proto = out.File
	file_question_set_msg_proto_rawDesc = nil
	file_question_set_msg_proto_goTypes = nil
	file_question_set_msg_proto_depIdxs = nil
}
